-- 2026年门店数据统计
SELECT a.month                                     AS '统计月份',
       SUM(main_business_income)                   AS '主营业务收入',
       SUM(service_fee)                            AS '服务费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(service_fee) / SUM(main_business_income), 4) END AS '服务费比例',
       SUM(project_commission)                     AS '推拿师成本-项目提成',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(project_commission) / SUM(main_business_income), 4) END AS '推拿师成本-项目提成比例',
       SUM(over_production_bonus)                  AS '推拿师成本-超产值奖金',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(over_production_bonus) / SUM(main_business_income), 4) END AS '推拿师成本-超产值奖金比例',
       SUM(promotion_subsidy)                      AS '推拿师成本-促销补贴',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(promotion_subsidy) / SUM(main_business_income), 4) END AS '推拿师成本-促销补贴比例',
       SUM(-cost_variance)                         AS '推拿师成本-推拿师成本差异',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(-cost_variance) / SUM(main_business_income), 4) END AS '推拿师成本-推拿师成本差异比例',
       SUM(repeat_customer_incentive)              AS '推拿师成本-回头客激励',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(repeat_customer_incentive) / SUM(main_business_income), 4) END AS '推拿师成本-回头客激励比例',
       SUM(masseur_commission)                     AS '推拿师成本-推拿师接待提成',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(masseur_commission) / SUM(main_business_income), 4) END AS '推拿师成本-推拿师接待提成比例',
       SUM(recruitment_fee)                        AS '推拿师成本-招聘费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(recruitment_fee) / SUM(main_business_income), 4) END AS '推拿师成本-招聘费比例',
       SUM(other_subsidy_money)                    AS '推拿师成本-其他补贴',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(other_subsidy_money) / SUM(main_business_income), 4) END AS '推拿师成本-其他补贴比例',
       SUM(tech_housing_subsidy)                   AS '推拿师成本-推拿师住房补贴',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(tech_housing_subsidy) / SUM(main_business_income), 4) END AS '推拿师成本-推拿师住房补贴比例',
       SUM(tech_social_security)                   AS '推拿师成本-推拿师社保费用',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(tech_social_security) / SUM(main_business_income), 4) END AS '推拿师成本-推拿师社保费用比例',
       SUM(replace_schedule_subsidy)               AS '推拿师成本-推拿师顶班补贴',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(replace_schedule_subsidy) / SUM(main_business_income), 4) END AS '推拿师成本-推拿师顶班补贴比例',
       SUM(refund_subsidy)                         AS '推拿师成本-退单补贴',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(refund_subsidy) / SUM(main_business_income), 4) END AS '推拿师成本-退单补贴比例',
       SUM(pre_job_training_reward)                AS '推拿师成本-岗前培训奖励',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(pre_job_training_reward) / SUM(main_business_income), 4) END AS '推拿师成本-岗前培训奖励比例',
       SUM(uniform_fee)                            AS '推拿师成本-工作服',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(uniform_fee) / SUM(main_business_income), 4) END AS '推拿师成本-工作服比例',
       SUM(dormitory_rental_cost)                  AS '推拿师成本-宿舍租金成本',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(dormitory_rental_cost) / SUM(main_business_income), 4) END AS '推拿师成本-宿舍租金成本比例',
       SUM(travel_expenses_supported)              AS '推拿师成本-外部员工支援差旅费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(travel_expenses_supported) / SUM(main_business_income), 4) END AS '推拿师成本-外部员工支援差旅费比例',
       SUM(store_dinner_expenses)                  AS '推拿师成本-新店聚餐费用',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(store_dinner_expenses) / SUM(main_business_income), 4) END AS '推拿师成本-新店聚餐费用比例',
       SUM(partner_gains_beans)                    AS '推拿师成本-三级合伙人获豆',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(partner_gains_beans) / SUM(main_business_income), 4) END AS '推拿师成本-三级合伙人获豆比例',
       SUM(tech_minimum_beans)                     AS '推拿师成本-保底获豆',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(tech_minimum_beans) / SUM(main_business_income), 4) END AS '推拿师成本-保底获豆比例',
       SUM(part_time_job_cost)                     AS '推拿师成本-兼职推拿师成本',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(part_time_job_cost) / SUM(main_business_income), 4) END AS '推拿师成本-兼职推拿师成本比例',
       SUM(cleaning_income)                        AS '客户经理成本-保洁工资收入',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(cleaning_income) / SUM(main_business_income), 4) END AS '客户经理成本-保洁工资收入比例',
       SUM(shift_commission)                       AS '客户经理成本-客户经理班次提成',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(shift_commission) / SUM(main_business_income), 4) END AS '客户经理成本-客户经理班次提成比例',
       SUM(new_customer_commission)                AS '客户经理成本-客户经理新客提成',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(new_customer_commission) / SUM(main_business_income), 4) END AS '客户经理成本-客户经理新客提成比例',
       SUM(manager_reception_commission)           AS '客户经理成本-客户经理接待提成',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(manager_reception_commission) / SUM(main_business_income), 4) END AS '客户经理成本-客户经理接待提成比例',
       SUM(rating_commission)                      AS '客户经理成本-客户经理评价提成',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(rating_commission) / SUM(main_business_income), 4) END AS '客户经理成本-客户经理评价提成比例',
       SUM(supplies_commission)                    AS '客户经理成本-客户经理物资提成',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(supplies_commission) / SUM(main_business_income), 4) END AS '客户经理成本-客户经理物资提成比例',
       SUM(manager_housing_subsidy)                AS '客户经理成本-客户经理住房补贴',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(manager_housing_subsidy) / SUM(main_business_income), 4) END AS '客户经理成本-客户经理住房补贴比例',
       SUM(manager_social_security)                AS '客户经理成本-客户经理社保费用',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(manager_social_security) / SUM(main_business_income), 4) END AS '客户经理成本-客户经理社保费用比例',
       SUM(hygiene_maintenance)                    AS '客户经理成本-卫生维护',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(hygiene_maintenance) / SUM(main_business_income), 4) END AS '客户经理成本-卫生维护比例',
       SUM(clean_toilet)                           AS '客户经理成本-打扫厕所',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(clean_toilet) / SUM(main_business_income), 4) END AS '客户经理成本-打扫厕所比例',
       SUM(clean_room)                             AS '客户经理成本-打扫房间',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(clean_room) / SUM(main_business_income), 4) END AS '客户经理成本-打扫房间比例',
       SUM(overtime_subsidy)                       AS '客户经理成本-加班补贴',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(overtime_subsidy) / SUM(main_business_income), 4) END AS '客户经理成本-加班补贴比例',
       SUM(manager_other_subsidy_money)            AS '客户经理成本-客户经理其他补贴',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(manager_other_subsidy_money) / SUM(main_business_income), 4) END AS '客户经理成本-客户经理其他补贴比例',
       SUM(fixed_rent)                             AS '变动成本-固定租金',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(fixed_rent) / SUM(main_business_income), 4) END AS '变动成本-固定租金比例',
       SUM(percentage_rent)                        AS '变动成本-提成租金',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(percentage_rent) / SUM(main_business_income), 4) END AS '变动成本-提成租金比例',
       SUM(promotion_fee)                          AS '变动成本-推广费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(promotion_fee) / SUM(main_business_income), 4) END AS '变动成本-推广费比例',
       SUM(property_fee)                           AS '变动成本-物管费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(property_fee) / SUM(main_business_income), 4) END AS '变动成本-物管费比例',
       SUM(depreciation_fee)                       AS '变动成本-折旧费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(depreciation_fee) / SUM(main_business_income), 4) END AS '变动成本-折旧费比例',
       SUM(linen_purchase_fee)                     AS '变动成本-布草采购费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(linen_purchase_fee) / SUM(main_business_income), 4) END AS '变动成本-布草采购费比例',
       SUM(washing_fee)                            AS '变动成本-布草洗涤费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(washing_fee) / SUM(main_business_income), 4) END AS '变动成本-布草洗涤费比例',
       SUM(consumables_purchase_fee)               AS '变动成本-消耗品采购费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(consumables_purchase_fee) / SUM(main_business_income), 4) END AS '变动成本-消耗品采购费比例',
       SUM(asset_maintenance_fee)                  AS '变动成本-资产维护费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(asset_maintenance_fee) / SUM(main_business_income), 4) END AS '变动成本-资产维护费比例',
       SUM(offline_ad_fee)                         AS '变动成本-线下广告费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(offline_ad_fee) / SUM(main_business_income), 4) END AS '变动成本-线下广告费比例',
       SUM(online_ad_fee)                          AS '变动成本-线上广告费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(online_ad_fee) / SUM(main_business_income), 4) END AS '变动成本-线上广告费比例',
       SUM(utilities_fee)                          AS '变动成本-水电费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(utilities_fee) / SUM(main_business_income), 4) END AS '变动成本-水电费比例',
       SUM(broadband_fee)                          AS '变动成本-宽带费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(broadband_fee) / SUM(main_business_income), 4) END AS '变动成本-宽带费比例',
       SUM(tax_and_surcharge)                      AS '变动成本-税金及附加费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(tax_and_surcharge) / SUM(main_business_income), 4) END AS '变动成本-税金及附加费比例',
       SUM(other_costs)                            AS '变动成本-其他',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(other_costs) / SUM(main_business_income), 4) END AS '变动成本-其他比例',
       SUM(after_sales_cost)                       AS '变动成本-售后费用',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(after_sales_cost) / SUM(main_business_income), 4) END AS '变动成本-售后费用比例',
       SUM(travel_expenses)                        AS '变动成本-差旅费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(travel_expenses) / SUM(main_business_income), 4) END AS '变动成本-差旅费比例',
       SUM(team_building_expenses)                 AS '变动成本-团建费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(team_building_expenses) / SUM(main_business_income), 4) END AS '变动成本-团建费比例',
       SUM(monitoring_fee)                         AS '变动成本-监控费',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(monitoring_fee) / SUM(main_business_income), 4) END AS '变动成本-监控费比例',
       SUM(labor_cost)                             AS '人工成本总计',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(labor_cost) / SUM(main_business_income), 4) END AS '人工成本总计比例',
       SUM(fixed_cost)                             AS '固定成本总计',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(fixed_cost) / SUM(main_business_income), 4) END AS '固定成本总计比例',
       SUM(variable_cost)                          AS '变动成本总计',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(variable_cost) / SUM(main_business_income), 4) END AS '变动成本总计比例',
       SUM(profit_before_tax)                      AS '税前利润',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(profit_before_tax) / SUM(main_business_income), 4) END AS '税前利润比例',
       SUM(income_tax)                             AS '所得税金额',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(income_tax) / SUM(main_business_income), 4) END AS '所得税金额比例',
       SUM(net_profit)                             AS '净利润',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(net_profit) / SUM(main_business_income), 4) END AS '净利润比例',
       SUM(net_cash_flow)                          AS '经营净现金流-经营净现金流',
       CASE WHEN SUM(main_business_income) = 0 THEN 0 ELSE ROUND(SUM(net_cash_flow) / SUM(main_business_income), 4) END AS '经营净现金流-经营净现金流比例',
       SUM(cum_net_cash_flow_mgmt)                 AS '累计经营净现金流-累计经营净现金流',
       SUM(round(payback_period, 2))               AS '投资回收期-投资回收期'
FROM data_warehouse.dws_profit_store_detail_monthly a
WHERE a.month >= '2026-01'
  AND a.month < DATE_FORMAT(CURDATE(), '%Y-%m')
GROUP BY a.month
ORDER BY a.month;

